service: ustc-pay-gov-test-server
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:service}-prod/*"

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-domain-manager

custom:
  subdomain: pay-gov-dev.ustaxcourt.gov
  customDomain:
    domainName: ${self:custom.subdomain}
    basePath: ""
    stage: ${self:provider.stage}
    autoDomain: true

functions:
  soap_api:
    handler: src/lambdas/handleSoapRequestLambda.handler
    events:
      - http:
          method: POST
          path: /wsdl
    environment:
      BASE_URL: ${self:custom.subdomain}
      BUCKET_NAME: ${self:service}-prod
      ACCESS_TOKEN: ${env:ACCESS_TOKEN}
      NODE_ENV: production

  soap_resource:
    handler: src/lambdas/getResourceLambda.handler
    events:
      - http:
          method: GET
          path: /wsdl/{filename}
      - http:
          method: GET
          path: /wsdl
    environment:
      BASE_URL: ${self:custom.subdomain}
      BUCKET_NAME: ${self:service}-prod
      ACCESS_TOKEN: ${env:ACCESS_TOKEN}
      NODE_ENV: production

  pay_page:
    handler: src/lambdas/getPayPageLambda.handler
    events:
      - http:
          method: GET
          path: /pay
    environment:
      BASE_URL: ${self:custom.subdomain}
      BUCKET_NAME: ${self:service}-prod
      ACCESS_TOKEN: ${env:ACCESS_TOKEN}
      NODE_ENV: production

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-prod
