service: ustc-pay-gov-test-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:service}-${opt:stage, 'dev'}/*"

package:
  individually: true

plugins:
  - serverless-esbuild

functions:
  soap_api:
    handler: src/lambdas/handleSoapRequestLambda.handler
    events:
      - http:
          method: POST
          path: /wsdl
    environment:
      BASE_URL: ${file(./config.${opt:stage, 'dev'}.yml):baseUrl}
      BUCKET_NAME: ${self:service}-${opt:stage, 'dev'}

  soap_resource:
    handler: src/lambdas/getResourceLambda.handler
    events:
      - http:
          method: GET
          path: /wsdl/{filename}
      - http:
          method: GET
          path: /wsdl
    environment:
      BASE_URL: ${file(./config.${opt:stage, 'dev'}.yml):baseUrl}
      BUCKET_NAME: ${self:service}-${opt:stage, 'dev'}

  pay_page:
    handler: src/lambdas/getPayPageLambda.handler
    events:
      - http:
          method: GET
          path: /pay
    environment:
      BASE_URL: ${file(./config.${opt:stage, 'dev'}.yml):baseUrl}
      BUCKET_NAME: ${self:service}-${opt:stage, 'dev'}

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${opt:stage, 'dev'}
        LifecycleConfiguration:
          Rules:
            - Id: DeleteObjectsAfter24Hours
              Status: Enabled
              ExpirationInDays: 1
